package enums;

public enum task {

	
	ADD_PATIENT,
	UPDATE_PATIENT, 
	GET_PATIENT,
	GET_USER,
	GET_LAB_REF,UPDATE_LAB_REF,
	CREATE_NEW_APPOINTMENT,GET_DOCTORS_IN_CLINIC_BY_TYPE,GET_AVAILIBLE_DOCTOR_HOURS,GET_OPEN_APPOINTMENTS,CANCEL_APPOINTMENT_FROM_DB,
	GET_ARRIVED_APPOINTMENTS,
	
	GET_PRIVATE_CLINIC_LIST,LOG_OUT,
	GET_CURRENT_APPOINTMENT_ID,
	SET_APPOINTMENT_RECORD,
	GET_SCHEDUELD_LAB,
	UPDATE_LAB_RECORD,
}
